name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allow pushing to branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Use the latest stable version

    - name: Build
      run: |
        python3 build.py

    - name: Deploy to Build Branch
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: build
        folder: api
        token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
